package ru.itmo.hls1.constant;

public enum LocationList {
        NEVSKY_PROSPEKT_1,
        PALACE_SQUARE_2,
        VASILEVSKY_ISLAND_3,
        PETER_AND_PAUL_FORTRESS_4,
        THE_HERMITAGE_MUSEUM_5,
        SMOLNY_CATHEDRAL_6,
        CATHERINE_PALACE_7,
        MARIINSKY_THEATRE_8,
        ST_ISAACS_CATHEDRAL_9,
        CHURCH_OF_THE_SAVIOR_ON_SPILLED_BLOOD_10,
        RUSSIAN_MUSEUM_11,
        PETERHOF_PALACE_12,
        SUMMER_GARDEN_13,
        BRONZE_HORSEMAN_MONUMENT_14,
        YUSUPOV_PALACE_15,
        ALEXANDER_NEVSKY_LAVRA_16,
        GRAND_MAKET_RUSSIA_INTERACTIVE_MUSEUM_17,
        ST_MICHAELS_CASTLE_18,
        ST_NICHOLAS_NAVAL_CATHEDRAL_19,
        FABERGE_MUSEUM_20,
        CRUISER_AURORA_21,
        LOMONOSOV_MOSCOW_STATE_UNIVERSITY_22,
        MIKHAILOVSKY_CASTLE_23,
        GRIBOEDOV_CANAL_24,
        THE_FIELD_OF_MARS_25;
}
